version: '3'

services:
  apachebench:
    image: httpd:2.4.48-alpine
    command: 'sh /httpd-script.sh'
    volumes:
      - ./httpd-script.sh:/httpd-script.sh
    depends_on:
      web:
        condition: service_healthy

  web:
    build: ./
    ports:
      - 8030:3000
    environment:
      # example of how to set an env var so that the yaml is valid
      - EXAMPLE=helloworld
      # uncomment to really see how bad it gets without caching
      # - SITEMAP_CACHE_MAX_AGE=1
      # uncomment to really see how bad it gets without caching
      # - CONCURRENCY=75
    healthcheck:
      test:
        - 'CMD'
        - 'node'
        - '-e'
        - 'net.connect(3000, process.exit.bind(0)).on("error", process.exit.bind(1))'
      interval: 2s
      timeout: 1s
      retries: 10
